### ISSUE TITLE
导航退出导航的监听在哪..点击退出导航返回不到上一个页面去

### ISSUE THREAD

**Issue by dahui888** [zrunker/ZAmap#2]
导航里的退出导航的监听在哪..点击退出导航返回不到上一个页面去

**Comment by zrunker** [comment]
你是指这个方法吗？&nbsp;AmapRouteActivityUtil exitNavi() 




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月11日(星期二) 上午10:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [zrunker/ZAmap] 导航退出导航的监听在哪..点击退出导航返回不到上一个页面去 (#2)





 
Closed #2.

**Comment by dahui888** [comment]
这个解决了,接口监听回调里加了个关闭就好了&nbsp; 就是进入导航页面 最下面有个退出导航 然后点了没反应&nbsp; 我看了那个对应方法里没有做对应的事件&nbsp; 我就回调出来写了个关闭的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zrunker/ZAmap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月11日(星期二) 中午1:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zrunker/ZAmap] 导航退出导航的监听在哪..点击退出导航返回不到上一个页面去 (#2)





 你是指这个方法吗？&amp;nbsp;AmapRouteActivityUtil exitNavi()  
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2021年5月11日(星期二) 上午10:41 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;;  
 主题: Re: [zrunker/ZAmap] 导航退出导航的监听在哪..点击退出导航返回不到上一个页面去 (#2) 
 
 
 
 
 
   
 Closed #2.
