### ISSUE TITLE
线路规划- 驾车规划的途经点怎么才能显示出来呢

### ISSUE THREAD

**Issue by dahui888** [zrunker/ZAmap#3]
线路规划- 驾车规划的途经点怎么才能显示出来呢

**Comment by zrunker** [comment]
设置maker
------&nbsp;原始邮件&nbsp;------
***@***.***&gt;;
发送时间:2021年5月13日(星期四)&nbsp;下午2:25
***@***.***&gt;;
***@***.***&gt;;
主题:[zrunker/ZAmap]&nbsp;线路规划-&nbsp;驾车规划的途经点怎么才能显示出来呢&nbsp;(#3)



 
线路规划- 驾车规划的途经点怎么才能显示出来呢
 
&mdash;

**Comment by zrunker** [comment]
能具体跟我说说你使用的是哪个类吗？ZMapView？我理解你要显示途径的需要调用 addMarker(LatLng latLng)方法。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zrunker/ZAmap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月20日(星期四) 上午8:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zrunker/ZAmap] 线路规划- 驾车规划的途经点怎么才能显示出来呢 (#3)





 
Closed #3.
